### ISSUE TITLE
Straight Quotation Mark [ " ] instead of [ in ] abbreviation for 'inch' unit in UnitValue object

### ISSUE THREAD

**Issue by detra** [adamdehaven/Specify#4] opened 2016-07-05 19:02 UTC
Thank you for your great script,
was looking to change/insert the 
abbreviation of " in"  to the abbreviation of **"**. 
Using the method of escaping the straight quotation mark " \""

On Line 304 
`case RulerUnits.Inches:
  v = new UnitValue(v, "pt").as("in");
  v = v.toFixed (decimals);
  unitsLabel = " in"; // add abbreviation
break;`

I switched out to

`case RulerUnits.Inches:
  v = new UnitValue(v, "pt").as("in");
  v = v.toFixed (decimals);
  unitsLabel = " \""; // add abbreviation
  break;`

**Comment by adamdehaven** [comment] 2016-07-06 12:30
I can confirm this works properly as an easy method of modifying one of unit abbreviations. Closing issue (as it's not a bug or issue), but good info for anyone else looking to modify the script in a similar way. Thanks!

**Closed as completed by adamdehaven** 2016-07-06 12:30 UTC
Labels: question

**Comment by detra** [comment] 2016-07-06 15:41
Happy to share and add to your fine script
