### ISSUE TITLE
Specify Dimensions Plugin for Adobe Illustrator - Extension missing

### ISSUE THREAD

**Issue by ImpressionAbbe** [adamdehaven/Specify#31] opened 2022-08-21 23:11 UTC
I've paid for the subscription for the Speccify Plugin for 5 different machines and now it has disappeared from Illustrator on all machines. I can't get it back. It's not in Creative Cloud plugins and when I go to Creative Cloud Exchange it wants me to buy it again. I have the order and subscription paid for and confirmation email.

**Comment by adamdehaven** [comment] 2022-08-21 23:22
@ImpressionAbbe let me check into this. 

In the meantime, I would recommend also emailing [asupport@adobe.com](asupport@adobe.com) and describe the issue as this seems to happen on their end from time to time (if you look through the closed Issues here labeled "Adobe error" you'll see what I mean).

You can also try closing all Adobe apps, logging out of the Creative Cloud desktop app, and then logging back in. 

Like I said, I'll also look into things on my end; however, nothing has changed with the extension since several months ago.

**Comment by adamdehaven** [comment] 2022-08-22 01:29
I looked into this a bit more and I'm not able to reproduce, so unfortunately, you're going to need to reach out to Adobe as I outlined above. On my M1 Mac Studio, the extension still appears and is working properly

![image](https://user-images.githubusercontent.com/2229946/185821682-e2c1d553-c81e-4f5d-bc65-5f006f7ae82b.png)

**Closed as completed by adamdehaven** 2022-08-22 01:29 UTC
Labels: adobe issue
